name: ENABLEMENT IT
favicon: null
layout_spectrum: 0.2719359858892858
typography_spectrum: 0.03595823189243674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.24803731683641672
  lightness: 0.019940074998885393
  saturation: 0.3696987156290561
  rhythmicContrast: 0.5151311885565519
purpose: []
